// <auto-generated />
using EFTEST;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ef_test.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFTEST.Customer", b =>
                {
                    b.Property<string>("account_id")
                        .HasColumnType("text");

                    b.Property<string>("account_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("annual_fee")
                        .HasColumnType("integer");

                    b.Property<string>("email_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("total_amount_spent")
                        .HasColumnType("double precision");

                    b.Property<string>("type_of_nonprofit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("account_id");

                    b.ToTable("YourEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
